### ISSUE TITLE
"class" keyword (and maybe more C++ keywords?) can be used as a variable name

### ISSUE THREAD

**Issue by eugenschindler** [qutorial/zplusplus#10]

**Comment by qutorial** [comment]
Fixed.

**Comment by qutorial** [comment]
See the TS test 
http://localhost:8080/select/ZPlusPlus/r:a6b7874d-480c-497e-8651-970d7add73fa/4256712340472461699/

**Comment by qutorial** [comment]
Use new mbeddr version (latest). See  http://mbeddr.fortiss.org/download/

**Comment by klemensschindler** [comment]
Class is now disallowed.

Tests have been added for all other reserved C++ keywords. Closing issue.
