### ISSUE TITLE
Classes declared outside a namespace in another module are not in the search scope

### ISSUE THREAD

**Issue by eugenschindler** [qutorial/zplusplus#34]
The class will not show up at all in the completion menu. Only if it is inside a namespace, then it will be in the menu.

**Comment by klemensschindler** [comment]
Classifiers were not collected from external modules. Fixed in  db81b55.

**Comment by eugenschindler** [comment]
Works now, correctness can be observed in http://localhost:8080/select/ZPlusPlus/r:0e6ada45-8c2c-4eca-b734-3ab26e55030d/4104398640834123743/
