### ISSUE TITLE
Implementation of a method is not checked

### ISSUE THREAD

**Issue by qutorial** [qutorial/zplusplus#5]
Signatures can differ

**Comment by klemensschindler** [comment]
More specific issues related to this issue:

Member function return type not updated automatically:
Changing the return type of a member function in the declaration, does not automatically change the return type in the implementation

Adding or changing a funcion parameter does not update the parameter in the implementation:
Although valid C++, having different names between declaration and definition is usually not desired.

**Comment by qutorial** [comment]
I suggest creating a TS rule which is going to check the correspondence. 
And an Error-Intention to fix it.
