### ISSUE TITLE
Arithmetic operators do not seem to work in currently used mbeddr version

### ISSUE THREAD

**Issue by klemensschindler** [qutorial/zplusplus#6]
Arithmetic operators seem to be broken in currently used version of mbeddr.

For example:

``` c++
int32  SomeClass::publicFunction(int32 n) from SomeClass { 
  int32 a = 1; 
  int32 b = a - 1;
  return 0;
}
```

Gives an error on the "a-1" expression: "- cannot be applied to uint32 and (uint8|uint8).

I did not report directly to the mbeddr list, because I don't know if it has already be fixed there.

**Comment by qutorial** [comment]
Fixed in the recent mbeddr. 
Update your mbeddr:
http://mbeddr.fortiss.org/download/updating/
