### ISSUE TITLE
Destructor should be added by default

### ISSUE THREAD

**Issue by albertg1984** [qutorial/zplusplus#8]
http://en.wikipedia.org/wiki/Rule_of_three_(C%2B%2B_programming)

**Comment by qutorial** [comment]
Added, see the concept constructor:
http://localhost:8080/select/ZPlusPlus/r:309fa391-fbb1-4e9e-aee7-425fefab09dd/4396928333263100999/

**Comment by klemensschindler** [comment]
Checked it, it works. Thanks!
