### ISSUE TITLE
Not possible to initialize a class "on the stack"

### ISSUE THREAD

**Issue by eugenschindler** [qutorial/zplusplus#9]
While we can write
`Class c* = new Class(arg);`
we cannot write
`Class c(arg);`

**Comment by qutorial** [comment]
This syntax is not supported, but 
C c = c(arg);
works.

You can extend the syntax, if you like the shortcut more

**Comment by klemensschindler** [comment]
I didn't manage to construct it like that. I can only do the following

``` cpp
MyClass c = MyClass()
```

But this is not the same, it does not allow MyClass to have constructor arguments and calls an assignment operator.

**Comment by RemiBosman** [comment]
Added first version of this, behaviour actions, constraints, etc.. need more work.

**Comment by klemensschindler** [comment]
Great, It is now possible to initialize classes as local vars on the stack for now!

Closing issue.
